export const queryKeys = {
  ServiceCategory_GetServiceCategoriesQuery:
    "ServiceCategory_GetServiceCategoriesQuery",
  serviceSubCategory_getAll: "serviceSubCategory_getAll",
  address_getMyAddresses: "address_getMyAddresses",
  serviceRequest_getMyRequests: "serviceRequest_getMyRequests",
  serviceRequest_getMyAcceptances: "serviceRequest_getMyAcceptances",
  city_getAll: "city_getAll",
  serviceRequest_getById: "serviceRequest_getById",
  neighborhood_getAll: "neighborhood_getAll",
  serviceTypeQuestion_getByServiceType: "serviceTypeQuestion_getByServiceType",
  banner_getAll: "banner_getAll",
  serviceRequest_getAvailableRequests: "serviceRequest_getAvailableRequests",
  discountCode_getMyCodes: "discountCode_getMyCodes",
  cancellationReason_getAll: "cancellationReason_getAll",
  province_getAll: "province_getAll",
  specialist_getMyProfile: "specialist_getMyProfile",
  user_updateProfile: "user_updateProfile",
  user_getMyProfile: "user_getMyProfile",
  specialist_getAll: "specialist_getAll",
  serviceTypes_getPopular: "serviceTypes_getPopular",
};
