query city_getAll(
  $skip: Int
  $take: Int
  $where: CityDtoFilterInput
  $order: [CityDtoSortInput!]
) {
  city_getAll {
    result(skip: $skip, take: $take, where: $where, order: $order) {
      items {
        id
        isActive
        name
        province {
          id
          name
        }
        activeCarousel {
          imageUrls
          id
          title
        }
        activeBanner {
          imageUrl
          id
          title
        }
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
      }
      totalCount
    }
    status
  }
}

query banner_getAll(
  $skip: Int
  $take: Int
  $where: BannerDtoFilterInput
  $order: [BannerDtoSortInput!]
) {
  banner_getAll {
    result(skip: $skip, take: $take, where: $where, order: $order) {
      items {
        id
        imageUrl
        title
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
      }
      totalCount
    }
    status
  }
}
