mutation address_create($input: AddAddressInput!) {
  address_create(input: $input) {
    status
  }
}

mutation address_update($input: UpdateAddressInput!) {
  address_update(input: $input) {
    status
  }
}
