query serviceTypes_getAll(
  $skip: Int
  $take: Int
  $order: [ServiceTypeDtoSortInput!]
  $where: ServiceTypeDtoFilterInput
) {
  serviceTypes_getAll {
    result(skip: $skip, take: $take, order: $order, where: $where) {
      pageInfo {
        hasNextPage
        hasPreviousPage
      }
      items {
        name
        logo
        id
        serviceSubCategoryId
      }
    }
    status
  }
}
