query serviceTypes_getAll(
  $skip: Int
  $take: Int
  $order: [ServiceTypeDtoSortInput!]
  $where: ServiceTypeDtoFilterInput
) {
  serviceTypes_getAll {
    result(skip: $skip, take: $take, order: $order, where: $where) {
      pageInfo {
        hasNextPage
        hasPreviousPage
      }
      items {
        name
        logo
        id
        fixedGender
        basePrice
        serviceSubCategory {
          id
          name
        }
      }
    }
    status
  }
}

query serviceRequest_getAvailableRequests(
  $input: GetAvailableRequestsInput!
  $skip: Int
  $take: Int
  $order: [AvailableServiceRequestDtoSortInput!]
  $where: AvailableServiceRequestDtoFilterInput
) {
  serviceRequest_getAvailableRequests(input: $input) {
    result(skip: $skip, take: $take, order: $order, where: $where) {
      pageInfo {
        hasNextPage
        hasPreviousPage
      }
      items {
        address {
          text
          city {
            id
            name
          }
        }

        finalPrice
        customer {
          firstName
          lastName
          phoneNumber
          profileImageUrl
          id
          gender
        }
        description
        requestDate
        id
        serviceType {
          name
          id
          logo
        }
        specialist {
          lastName
          firstName
          id
          profileImageUrl
          rateCount
          phoneNumber
        }
        status
      }
    }
    status
  }
}

query serviceTypes_getPopular(
  $input: GetPopularServiceTypesInput!
  $skip: Int
  $take: Int
  $order: [PopularServiceTypeDtoSortInput!]
  $where: PopularServiceTypeDtoFilterInput
) {
  serviceTypes_getPopular(input: $input) {
    result(skip: $skip, take: $take, order: $order, where: $where) {
      pageInfo {
        hasNextPage
        hasPreviousPage
      }
      items {
        name
        logo
        id
        fixedGender
        basePrice
        requestCount
        serviceSubCategory {
          id
          name
        }
      }
    }
    status
  }
}
