query disabledServiceTime(
  $skip: Int
  $take: Int
  $where: DisabledServiceTimeDtoFilterInput
) {
  disabledServiceTime_getAll {
    result(skip: $skip, take: $take, where: $where) {
      totalCount
      items {
        time
        id
      }
    }
    status
  }
}
