query serviceTypeQuestion_getByServiceType(
  $input: GetServiceTypeQuestionsByServiceTypeInput!
  $skip: Int
  $take: Int
) {
  serviceTypeQuestion_getByServiceType(input: $input) {
    result(take: $take, skip: $skip) {
      items {
        id
        text
        isRequired
        options {
          text
          price
          id
        }
        questionType
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
      }
    }
    status
  }
}
