mutation auth_requestOtp($phoneNumber: String!, $userType: UserType!) {
  auth_requestOtp(phoneNumber: $phoneNumber, userType: $userType) {
    status
  }
}

mutation auth_verifyOtp(
  $phoneNumber: String!
  $userType: UserType!
  $otp: String!
) {
  auth_verifyOtp(phoneNumber: $phoneNumber, userType: $userType, otp: $otp) {
    status
    result {
      accessToken
      refreshToken
    }
  }
}

mutation auth_refreshToken($accessToken: String!, $refreshToken: String!) {
  auth_refreshToken(accessToken: $accessToken, refreshToken: $refreshToken) {
    status
    result {
      accessToken
      refreshToken
    }
  }
}
