mutation auth_requestOtp($input: RequestOtpInput!) {
  auth_requestOtp(input: $input) {
    status
  }
}

mutation auth_verifyOtp($input: VerifyOtpInput!) {
  auth_verifyOtp(input: $input) {
    status
    result {
      accessToken
      refreshToken
    }
  }
}

mutation auth_refreshToken($input: RefreshTokenInput!) {
  auth_refreshToken(input: $input) {
    status
    result {
      accessToken
      refreshToken
    }
  }
}
