query serviceCategory_getServiceCategories(
  $skip: Int
  $take: Int
  $where: ServiceCategoryDtoFilterInput
  $order: [ServiceCategoryDtoSortInput!]
) {
  serviceCategory_getServiceCategories {
    result(skip: $skip, take: $take, where: $where, order: $order) {
      items {
        name
        logo
        id
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
      }
    }
    status
  }
}

query serviceCategory_getServiceCategory($id: UUID!) {
  serviceCategory_getServiceCategory(id: $id) {
    result {
      name
      logo
      id
    }
    status
  }
}
