query serviceCategory_getServiceCategories(
  $skip: Int
  $take: Int
  $order: [ServiceCategoryDtoSortInput!]
  $where: ServiceCategoryDtoFilterInput
) {
  serviceCategory_getServiceCategories(
    skip: $skip
    take: $take
    order: $order
    where: $where
  ) {
    pageInfo {
      hasNextPage
      hasPreviousPage
    }
    items {
      name
      logo
      id
    }
  }
}

query serviceCategory_getServiceCategory($id: UUID!) {
  serviceCategory_getServiceCategory(id: $id) {
    name
    logo
    id
  }
}
