mutation serviceRequest_accept($input: AcceptServiceRequestInput!) {
  serviceRequest_accept(input: $input) {
    status
    result {
      id
    }
  }
}

mutation serviceRequest_cancel($input: CancelServiceRequestInput!) {
  serviceRequest_cancel(input: $input) {
    status
    result {
      id
    }
  }
}

mutation serviceRequest_reject($input: RejectServiceRequestInput!) {
  serviceRequest_reject(input: $input) {
    status
    result {
      serviceRequest {
        id
      }
    }
  }
}

mutation serviceRequest_markAsArrived($input: MarkAsArrivedInput!) {
  serviceRequest_markAsArrived(input: $input) {
    status
    result {
      id
    }
  }
}

mutation serviceRequest_completeService($input: CompleteServiceInput!) {
  serviceRequest_completeService(input: $input) {
    status
    result {
      id
    }
  }
}

mutation payment_create($input: CreatePaymentInput!) {
  payment_create(input: $input) {
    status
    result {
      id
      paymentUrl
    }
  }
}

mutation serviceRequest_applyDiscount(
  $input: ApplyDiscountCodeToServiceRequestInput!
) {
  serviceRequest_applyDiscount(input: $input) {
    status
    result {
      id
      basePrice
      finalPrice
    }
  }
}

mutation serviceRequest_removeDiscount(
  $input: RemoveDiscountCodeFromServiceRequestInput!
) {
  serviceRequest_removeDiscount(input: $input) {
    status
    result {
      id
      basePrice
      finalPrice
    }
  }
}
