query serviceRequest_getMyRequests(
  $skip: Int
  $take: Int
  $where: ServiceRequestDtoFilterInput
  $order: [ServiceRequestDtoSortInput!]
) {
  serviceRequest_getMyRequests {
    result(skip: $skip, take: $take, where: $where, order: $order) {
      items {
        addressText
        customerName
        description
        id
        requestDate
        status
        serviceTypeName
        specialistName
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
      }
      totalCount
    }
    status
  }
}

query serviceRequest_getMyAcceptances(
  $skip: Int
  $take: Int
  $where: ServiceRequestDtoFilterInput
  $order: [ServiceRequestDtoSortInput!]
) {
  serviceRequest_getMyAcceptances {
    result(skip: $skip, take: $take, where: $where, order: $order) {
      items {
        addressText
        customerName
        description
        requestDate
        id
        serviceTypeName
        specialistName
        status
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
      }
      totalCount
    }
    status
  }
}

query serviceRequest_getById($id: UUID!) {
  serviceRequest_getById(id: $id) {
    result {
      addressText
      customerName
      description
      requestDate
      id
      serviceTypeName
      specialistName
      status
    }
    status
  }
}
