query serviceRequest_getMyRequests(
  $skip: Int
  $take: Int
  $where: ServiceRequestDtoFilterInput
  $order: [ServiceRequestDtoSortInput!]
) {
  serviceRequest_getMyRequests {
    result(skip: $skip, take: $take, where: $where, order: $order) {
      items {
        address {
          text
        }
        customer {
          lastName
          firstName
          phoneNumber
        }
        description
        id
        requestDate
        status
        serviceType {
          name
          id
        }
        specialist {
          lastName
          firstName
          id
          profileImageUrl
        }
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
      }
      totalCount
    }
    status
  }
}

query serviceRequest_getMyAcceptances(
  $skip: Int
  $take: Int
  $where: ServiceRequestDtoFilterInput
  $order: [ServiceRequestDtoSortInput!]
) {
  serviceRequest_getMyAcceptances {
    result(skip: $skip, take: $take, where: $where, order: $order) {
      items {
        address {
          text
          latitude
          longitude
          neighborhoodId
        }
        cancellationReason {
          id
          name
        }
        customer {
          firstName
          lastName
          phoneNumber
          profileImageUrl
          id
          gender
        }
        description
        requestDate
        id
        serviceType {
          name
          id
          logo
        }
        specialist {
          lastName
          firstName
          id
          profileImageUrl
          rateCount
          phoneNumber
        }
        status
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
      }
      totalCount
    }
    status
  }
}

query serviceRequest_getById($id: UUID!) {
  serviceRequest_getById(id: $id) {
    result {
      address {
        text
        latitude
        longitude
        neighborhoodId
      }
      cancellationReason {
        id
        name
      }
      customer {
        firstName
        lastName
        phoneNumber
        profileImageUrl
        id
        gender
      }
      description
      requestDate
      id
      serviceType {
        name
        id
        logo
      }
      specialist {
        lastName
        firstName
        id
        profileImageUrl
        rateCount
        phoneNumber
      }
      status
    }
    status
  }
}
