query neighborhood_getAll(
  $skip: Int
  $take: Int
  $where: NeighborhoodDtoFilterInput
  $order: [NeighborhoodDtoSortInput!]
) {
  neighborhood_getAll {
    result(order: $order, skip: $skip, take: $take, where: $where) {
      items {
        name
        id
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
      }
      totalCount
    }
  }
}
