query revenue_getMyRevenue($daySD: DateTime!, $dayED: DateTime!) {
  revenue_getMyRevenue(input: { startDate: $daySD, endDate: $dayED }) {
    status
    result {
      totalAmount
    }
  }
}

query getMyRevenue($input: GetMyRevenueInput!) {
  revenue_getMyRevenue(input: $input) {
    status
    result {
      totalAmount
      unsettledAmount
    }
  }
}
