query serviceSubCategory_getAll(
  $skip: Int
  $take: Int
  $order: [ServiceSubCategoryDtoSortInput!] #$where: ServiceSubCategoryDtoFilterInput
) {
  serviceSubCategory_getAll(
    skip: $skip
    take: $take
    order: $order #where: $where
  ) {
    pageInfo {
      hasNextPage
      hasPreviousPage
    }
    items {
      id
      logo
      name
      serviceCategoryId
    }
  }
}

query serviceSubCategory_get($id: UUID!) {
  serviceSubCategory_get(id: $id) {
    id
    logo
    name
    serviceCategoryId
  }
}
