query serviceSubCategory_getAll(
  $skip: Int
  $take: Int
  $order: [ServiceSubCategoryDtoSortInput!]
  $where: ServiceSubCategoryDtoFilterInput
) {
  serviceSubCategory_getAll {
    result(skip: $skip, take: $take, order: $order, where: $where) {
      pageInfo {
        hasNextPage
        hasPreviousPage
      }
      items {
        id
        logo
        name
        serviceCategory {
          id
        }
      }
    }
    status
  }
}

query serviceSubCategory_getById($input: GetServiceSubCategoryByIdInput!) {
  serviceSubCategory_getById(input: $input) {
    result {
      id
      logo
      name
      serviceCategory {
        id
      }
    }
    status
  }
}
