mutation user_updateProfile($input: UpdateUserProfileInput!) {
  user_updateProfile(input: $input) {
    status
    result {
      id
    }
  }
}

mutation specialist_updateSpecializedDocuments(
  $input: UpdateSpecializedDocumentsInput!
) {
  specialist_updateSpecializedDocuments(input: $input) {
    status
  }
}

mutation specialist_updateIdentityVerificationVideo(
  $input: UpdateIdentityVerificationVideoInput!
) {
  specialist_updateIdentityVerificationVideo(input: $input) {
    status
  }
}

mutation specialist_updateSpecializedDocuments(
  $input: UpdateSpecializedDocumentsInput!
) {
  specialist_updateSpecializedDocuments(input: $input) {
    status
  }
}

mutation specialist_setPersonalInformation(
  $input: SetPersonalInformationInput!
) {
  specialist_setPersonalInformation(input: $input) {
    status
  }
}

mutation specialist_setLocationAndSpecialty(
  $input: SetLocationAndSpecialtyInput!
) {
  specialist_setLocationAndSpecialty(input: $input) {
    result {
      id
    }
    status
  }
}
