query user_getMyProfile {
  user_getMyProfile {
    status
    result {
      id
      phoneNumber
      firstName
      gender
      lastName
      profileImageUrl
    }
  }
}

query address_getMyAddresses(
  $skip: Int
  $take: Int
  $where: AddressDtoFilterInput
  $order: [AddressDtoSortInput!]
) {
  address_getMyAddresses {
    result(skip: $skip, take: $take, where: $where, order: $order) {
      items {
        id
        location {
          latitude
          longitude
        }
        neighborhood {
          id
          city {
            name
            id
          }
          name
        }
        text
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
      }
    }
    status
  }
}

query discountCode_getAll(
  $skip: Int
  $take: Int
  $where: DiscountCodeDtoFilterInput
  $order: [DiscountCodeDtoSortInput!]
) {
  discountCode_getAll {
    result(skip: $skip, take: $take, where: $where, order: $order) {
      items {
        id
        amount
        code
        expiryDate
        isActive
        isPercentage
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
      }
    }
    status
  }
}

query specialist_getMyProfile {
  specialist_getMyProfile {
    status
    result {
      city {
        id
        name
        province {
          id
          name
        }
      }
      averageRating
      rateCount
      birthDate
      id
      firstName
      lastName
      idCardImageUrl
      daysRegistered
      phoneNumber
      successfulMissions
      idCardVerificationStatus
      identityVerificationVideoStatus
      identityVerificationVideoUrl
      serviceSubCategory {
        id
        logo
        name
        serviceCategory {
          id
          logo
          name
        }
      }
      serviceTypes {
        id
        logo
        name
      }
      specializedDocumentsVerificationStatus
      specializedDocumentUrls
    }
  }
}

query province_getAll(
  $skip: Int
  $take: Int
  $where: ProvinceDtoFilterInput
  $order: [ProvinceDtoSortInput!]
) {
  province_getAll {
    result(skip: $skip, take: $take, where: $where, order: $order) {
      items {
        id
        name
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
      }
    }
    status
  }
}
