query user_getMyProfile {
  user_getMyProfile {
    status
    result {
      id
      phoneNumber
    }
  }
}

query address_getMyAddresses(
  $skip: Int
  $take: Int
  $where: AddressDtoFilterInput
  $order: [AddressDtoSortInput!]
) {
  address_getMyAddresses {
    result(skip: $skip, take: $take, where: $where, order: $order) {
      items {
        id
        latitude
        longitude
        neighborhoodId
        text
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
      }
    }
    status
  }
}

query discountCode_getAll(
  $skip: Int
  $take: Int
  $where: DiscountCodeDtoFilterInput
  $order: [DiscountCodeDtoSortInput!]
) {
  discountCode_getAll {
    result(skip: $skip, take: $take, where: $where, order: $order) {
      items {
        id
        amount
        code
        expiryDate
        isActive
        isPercentage
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
      }
    }
    status
  }
}
