query user_getMyProfile {
  user_getMyProfile {
    status
    result {
      id
      phoneNumber
    }
  }
}

query address_getMyAddresses(
  $skip: Int
  $take: Int
  $userId: UUID!
  $where: AddressDtoFilterInput
  $order: [AddressDtoSortInput!]
) {
  address_getMyAddresses(userId: $userId) {
    result(skip: $skip, take: $take, where: $where, order: $order) {
      items {
        id
        latitude
        longitude
        neighborhoodId
        text
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
      }
    }
    status
  }
}
